services:
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ENV_VAR=your_value
    volumes:
      - ./config/config.json:/app/config.json
      - ./data:/app/data
